Devsh-Graphics-Programming/Nabla

- include/IVideoDriver.h
- include/irr/video/IGPUCommandBuffer.h
- include/irr/video/IGPUPrimaryCommandBuffer.h
- include/irr/video/IGPUQueue.h
- include/irr/video/IGPUQueueFamily.h
Discussion in https://github.com/Devsh-Graphics-Programming/Nabla/issues/3
> Command buffer and queue interfaces

- include/nbl/builtin/glsl/format/encode.glsl
> Fixed RGB19E7 encode in GLSL

- examples_tests/22.RaytracedAO/Renderer.cpp
- include/nbl/ext/MitsubaLoader/CElementEmitter.h
- include/nbl/ext/MitsubaLoader/SContext.h
- src/nbl/ext/MitsubaLoader/CMitsubaLoader.cpp
- src/nbl/ext/RadeonRays/RadeonRays.cpp
- src/nbl/video/COpenGLCommon.h
Merge whenever you want, however GL enum color functions need some more touch
> Fixes for ex 22

- source/Nabla/COpenGLDriver.h
- src/nbl/ext/RadeonRays/RadeonRays.cpp
- src/nbl/video/COpenGLCommon.h
> Ex22 and other minor fixes

- examples_tests/18.MitsubaLoader/main.cpp
- include/nbl/core/algorithm/radix_sort.h
- include/nbl/core/core.h
- src/nbl/asset/utils/COverdrawMeshOptimizer.cpp
- src/nbl/asset/utils/CSmoothNormalGenerator.cpp
> Radix sort

- examples_tests/49.ComputeFFT/fft_convolve_ifft.comp
- examples_tests/49.ComputeFFT/normalization.comp
- include/nbl/builtin/glsl/ext/FFT/default_compute_fft.comp
- include/nbl/ext/FFT/FFT.h
> moar cleanup

- examples_tests/39.DenoiserTonemapper/main.cpp
> change meta API - missing one from my previous denoiser work

- examples_tests/39.DenoiserTonemapper/CommonPushConstants.h
- examples_tests/39.DenoiserTonemapper/ShaderCommon.glsl
- examples_tests/39.DenoiserTonemapper/main.cpp
- include/nbl/core/algorithm/radix_sort.h
- include/nbl/video/IGPUObjectFromAssetConverter.h
- src/nbl/video/COpenGLSpecializedShader.cpp
Bugfixes for descriptor sets, radix_sort, etc.
> Core bugfixes

- examples_tests/23.Autoexposure/main.cpp
- examples_tests/39.DenoiserTonemapper/CommonPushConstants.h
- examples_tests/39.DenoiserTonemapper/ShaderCommon.glsl
- examples_tests/39.DenoiserTonemapper/main.cpp
- include/nbl/builtin/glsl/ext/FFT/default_compute_fft.comp
- include/nbl/builtin/glsl/ext/LumaMeter/common.glsl
- include/nbl/builtin/glsl/ext/LumaMeter/impl.glsl
- include/nbl/ext/FFT/FFT.h
Denoising 16k images used to fail.
Tested with a 1GB EXR file provided by ditt.nl (not in this repo)
Make it work
> 16k denoiser

- examples_tests/22.RaytracedAO/Renderer.cpp
- examples_tests/22.RaytracedAO/main.cpp
- examples_tests/22.RaytracedAO/raytraceCommon.glsl
- examples_tests/22.RaytracedAO/virtualGeometry.glsl
> Pack UV and Normal into one attribute

- README.md
- include/nbl/builtin/glsl/barycentric/extensions.glsl
- source/Nabla/COpenGLExtensionHandler.cpp
- src/nbl/builtin/CMakeLists.txt
- src/nbl/video/COpenGLShader.h
> Added barycentric extensions

- CMakeLists.txt
- examples_tests/01.HelloWorld/main.cpp
- examples_tests/02.ComputeShader/main.cpp
- examples_tests/10.AllocatorTest/main.cpp
- examples_tests/29.SpecializationConstants/main.cpp
- examples_tests/33.Draw3DLine/main.cpp
- src/nbl/asset/IAssetManager.cpp
> Fixed examples compile errors

- include/nbl/builtin/glsl/bxdf/fresnel.glsl
> fresnel eta convention comment

- examples_tests/29.SpecializationConstants/main.cpp
- include/nbl/core/EventDeferredHandler.h
- include/nbl/video/ILogicalDevice.h
- include/nbl/video/alloc/SubAllocatedDataBuffer.h
- src/nbl/video/COpenGLConnection.cpp
- src/nbl/video/COpenGL_LogicalDevice.h
- src/nbl/video/IOpenGL_LogicalDevice.h
> Deferred event handler fix

- .gitmodules
- examples_tests/20.Megatexture/main.cpp
- examples_tests/22.RaytracedAO/Renderer.cpp
- examples_tests/22.RaytracedAO/main.cpp
- include/nbl/asset/filters/CBlitImageFilter.h
- include/nbl/asset/filters/CNormalMapToDerivativeFilter.h
- include/nbl/asset/material_compiler/CMaterialCompilerGLSLBackendCommon.h
- include/nbl/asset/utils/CDerivativeMapCreator.h
- include/nbl/asset/utils/ICPUVirtualTexture.h
- include/nbl/asset/utils/IVirtualTexture.h
- include/nbl/builtin/glsl/virtual_texturing/impl_functions.glsl
- include/nbl/ext/MitsubaLoader/CElementBSDF.h
- include/nbl/ext/MitsubaLoader/CElementSensor.h
- include/nbl/ext/MitsubaLoader/CMitsubaMaterialCompilerFrontend.h
- include/nbl/ext/MitsubaLoader/CMitsubaMetadata.h
- include/nbl/ext/MitsubaLoader/SContext.h
- include/nbl/macros.h
- src/nbl/asset/interchange/CImageLoaderTGA.cpp
- src/nbl/asset/material_compiler/CMaterialCompilerGLSLBackendCommon.cpp
- src/nbl/asset/utils/CDerivativeMapCreator.cpp
- src/nbl/ext/MitsubaLoader/CElementSensor.cpp
- src/nbl/ext/MitsubaLoader/CMitsubaLoader.cpp
- src/nbl/ext/MitsubaLoader/CMitsubaMaterialCompilerFrontend.cpp
> VT and material compiler/mitsuba loader fixes (normal map support)

- examples_tests/22.RaytracedAO/Renderer.cpp
- include/nbl/ext/MitsubaLoader/CMitsubaMetadata.h
> interesting crashbug in release mode @AnastazIuk investigate!

- src/nbl/video/COpenGL_LogicalDevice.h
- src/nbl/video/IOpenGL_LogicalDevice.h
@Crisspl review my fix for non-greedy fences, if all good then merge
<!-
By creating this pull request into Nabla, you agree to release all your past (even from previous commits) and present contributions in the Nabla repository under the Apache 2.0 license. If you're not the sole contributor, ensure that all contributors have signed the CLA agreeing to this.
-->
> Non-blocking wait for fences

- CMakeLists.txt
- examples_tests/06.MeshLoaders/main.cpp
- examples_tests/17.SimpleBulletIntegration/main.cpp
- examples_tests/common/CommonAPI.h
- include/SViewFrustum.h
- include/nabla.h.in
- src/nbl/CMakeLists.txt
- src/nbl/asset/IAssetManager.cpp
we need to resolve include errors first
> New API examples porting

- CMakeLists.txt
- include/nbl/asset/utils/CDirQuantCacheBase.h
- include/nbl/asset/utils/IIncludeHandler.h
- include/nbl/asset/utils/ISPIRVOptimizer.h
- include/nbl/core/containers/CCircularBuffer.h
- include/nbl/system/IAsyncQueueDispatcher.h
- include/nbl/system/ICancellableAsyncQueueDispatcher.h
- include/nbl/system/ILogger.h
- include/nbl/system/SReadWriteSpinLock.h
- include/nbl/ui/CWindowManagerWin32.h
- include/nbl/ui/IInputEventChannel.h
- src/nbl/asset/utils/ISPIRVOptimizer.cpp
- src/nbl/video/COpenGL_Queue.h
- src/nbl/video/IOpenGL_LogicalDevice.h
> How do you like them synchronisation apples

- examples_tests/17.SimpleBulletIntegration/Camera.hpp
- examples_tests/17.SimpleBulletIntegration/main.cpp
- examples_tests/33.Draw3DLine/main.cpp
- examples_tests/53.Transformations/CMakeLists.txt
- examples_tests/53.Transformations/main.cpp
- examples_tests/CMakeLists.txt
- examples_tests/common/CommonAPI.h
> Erfan examples update

- examples_tests/17.SimpleBulletIntegration/Camera.hpp
- examples_tests/17.SimpleBulletIntegration/main.cpp
- examples_tests/33.Draw3DLine/main.cpp
- examples_tests/53.Transformations/CMakeLists.txt
- examples_tests/53.Transformations/main.cpp
- examples_tests/CMakeLists.txt
- examples_tests/common/CommonAPI.h
- include/nbl/system/IAsyncQueueDispatcher.h
- include/nbl/system/ICancellableAsyncQueueDispatcher.h
> Cancel future fix

- examples_tests/38.EXRSplit/main.cpp
- src/nbl/asset/interchange/CImageLoaderOpenEXR.cpp
- src/nbl/asset/interchange/CImageWriterOpenEXR.cpp
performed tests on 38. example
> OpenEXR loader and writer on IFIle system

- .gitmodules
> submodule screwup fix

- examples_tests/55.RGB18E7S3/CMakeLists.txt
- examples_tests/55.RGB18E7S3/computeShader.comp
- examples_tests/55.RGB18E7S3/main.cpp
- examples_tests/CMakeLists.txt
- examples_tests/common/CommonAPI.h
- include/nbl/builtin/glsl/format/encode.glsl
- include/nbl/core/math/floatutil.h
- include/nbl/core/math/intutil.h
- include/nbl/system/IThreadHandler.h
- src/nbl/video/COpenGL_LogicalDevice.h
- src/nbl/video/COpenGL_Queue.h
- src/nbl/video/COpenGL_Swapchain.h
> Fix GL requests before Thread Handler init 

- include/nbl/video/utilities/IGPUObjectFromAssetConverter.h
> fix a big streaming buffer deferred free bug

- include/nbl/video/IPhysicalDevice.h
- src/nbl/CMakeLists.txt
- src/nbl/video/IOpenGL_PhysicalDeviceBase.h
@achalpandeyy please implement on Vulkan
> Draw Indirect Caps

- examples_tests/06.MeshLoaders/main.cpp
- include/nbl/asset/IAssetManager.h
- include/nbl/system/CFileWin32.h
- include/nbl/system/CSystemWin32.h
- include/nbl/system/IFileArchive.h
- src/nbl/asset/interchange/COBJMeshFileLoader.cpp
- src/nbl/system/CArchiveLoaderTar.cpp
- src/nbl/system/CArchiveLoaderZIp.cpp
- src/nbl/system/ISystem.cpp
> Archive loader fixes

- include/nbl/video/utilities/IGPUObjectFromAssetConverter.h
- src/nbl/video/COpenGLCommandBuffer.cpp
- src/nbl/video/COpenGLCommandBuffer.h
- src/nbl/video/COpenGLCommon.h
- src/nbl/video/COpenGL_LogicalDevice.h
- src/nbl/video/COpenGL_Queue.h
> GLES barriers

- include/nbl/video/utilities/IPropertyPool.h
> Fix contiguous property pool faulty debug alloc tracking assert

- examples_tests/54.Transformations/main.cpp
- include/nbl/builtin/glsl/transform_tree/debug.vert
- include/nbl/scene/ITransformTreeManager.h
> Fixes for Ex54 and the Debug Shader

- examples_tests/48.ArithmeticUnitTest/main.cpp
- include/nbl/video/utilities/CDumbPresentationOracle.h
> ex 48 fixes

- examples_tests/14.ComputeScan/main.cpp
- examples_tests/common/CommonAPI.h
- include/nbl/ui/CGraphicalApplicationAndroid.h
> @AnastaZluk non-graphical apps can build now

- src/nbl/CMakeLists.txt
- tools/debug/VisualStudio/DynamicArrayVisualizer.natvis
> Przemog visualizer

- cmake/common.cmake
- include/nbl/video/COpenGLSync.h
- src/nbl/CMakeLists.txt
> Build system fix

- src/nbl/video/CVulkanCommandBuffer.h
> Vulkan Backend

- include/nbl/asset/format/EFormat.h
- include/nbl/asset/format/impl/EFormat_getBlockDimensions.h
- include/nbl/asset/format/impl/EFormat_getFormatClass.h
- include/nbl/asset/format/impl/EFormat_getFormatClassBlockBytesize.h
- include/nbl/system/IApplicationFramework.h
- include/nbl/ui/IGraphicalApplicationFramework.h
- include/nbl/video/IPhysicalDevice.h
- include/nbl/video/utilities/IGPUVirtualTexture.h
Extends E_FORMAT_CLASS enum and adds implementations for them, to make it closer to the Vulkan compatibility classes: https://registry.khronos.org/vulkan/specs/1.2-extensions/html/chap43.html#formats-compatibility-classes
Implements BC, ETC and ASTC classes.
> Erfan image upload utils changes

- include/nbl/system/IApplicationFramework.h
- include/nbl/ui/IGraphicalApplicationFramework.h
Applies small changes to the application framework for resizing maintenance 2, sister PR: https://github.com/Devsh-Graphics-Programming/Nabla-Examples-and-Tests/pull/12
> Resizing maintenance v2

- include/nbl/builtin/glsl/ext/EnvmapImportanceSampling/measure_luma.comp
> Improved envmap

- src/nbl/ext/EnvmapImportanceSampling/EnvmapImportanceSampling.cpp
…ond regularization, ergo dark renders!
> Final Envmap fix!

- include/nbl/asset/IAsset.h
- include/nbl/asset/IAssetManager.h
- include/nbl/asset/ICPUBuffer.h
- include/nbl/asset/filters/CBasicImageFilterCommon.h
- include/nbl/asset/interchange/IAssetLoader.h
- include/nbl/asset/utils/CHLSLCompiler.h
- include/nbl/video/CVulkanSwapchain.h
- include/nbl/video/IDeviceMemoryBacked.h
- include/nbl/video/IGPUFence.h
- include/nbl/video/ILogicalDevice.h
- include/nbl/video/utilities/CPropertyPoolHandler.h
- include/nbl/video/utilities/IUtilities.h
- src/nbl/asset/utils/CGLSLCompiler.cpp
- src/nbl/asset/utils/CHLSLCompiler.cpp
- src/nbl/video/CVulkanLogicalDevice.h
Exposes some Nabla APIs using NABLA_API
> Expose Nabla APIs

- include/nbl/system/ISystemPOSIX.h
- src/nbl/system/CSystemLinux.cpp
- src/nbl/system/ISystemPOSIX.cpp
address some compiling issues with ISystemPOSIX.
> address compiling problems with POSIX/linux CSystemLinux

- include/matrix4SIMD_impl.h
- include/nbl/asset/IBuffer.h
- include/nbl/asset/IDescriptorSetLayout.h
- include/nbl/asset/IRenderpassIndependentPipeline.h
- include/nbl/asset/ISkeleton.h
- include/nbl/asset/metadata/CGLTFMetadata.h
- include/nbl/asset/utils/CGLSLCompiler.h
- include/nbl/core/containers/refctd_dynamic_array.h
- include/nbl/core/util/bitflag.h
- include/nbl/system/IFileArchive.h
- include/nbl/system/ISystem.h
- include/nbl/system/ISystemPOSIX.h
- include/nbl/type_traits.h
- include/nbl/video/IDeviceMemoryAllocation.h
- include/nbl/video/IGPUShader.h
- include/nbl/video/IPhysicalDevice.h
- include/nbl/video/utilities/IPropertyPool.h
- src/nbl/asset/interchange/CGLTFLoader.cpp
- src/nbl/asset/interchange/CGLTFLoader.h
- src/nbl/asset/interchange/COBJMeshFileLoader.cpp
- src/nbl/asset/interchange/CSPVLoader.cpp
- src/nbl/asset/interchange/CSTLMeshWriter.cpp
- src/nbl/asset/utils/CMeshManipulator.cpp
- src/nbl/system/IFileArchive.cpp
- src/nbl/video/CVulkanPhysicalDevice.h
this attempts to address some of the build problems partially on linux.  
verify this changes compile for windows should be sufficient.
> add missing includes for non PCH build

- include/nbl/ext/MitsubaLoader/CElementBSDF.h
- include/nbl/ext/MitsubaLoader/CElementTexture.h
> fix crash in non-Debug builds

- tests/22.RaytracedAO/test.py
Adds a display of exr files to the CI HTML result page
> CI exr viewer in browser

- include/nbl/system/IAsyncQueueDispatcher.h
- src/nbl/system/DefaultFuncPtrLoader.cpp
- src/nbl/video/IAPIConnection.cpp
another set of minor changes that address compiling problems for gcc
> bugfix: address compiling problems on linux

- include/nbl/asset/ISampler.h
- include/nbl/scene/ICullingLoDSelectionSystem.h
- include/nbl/video/SPhysicalDeviceFeatures.h
- include/nbl/video/SPhysicalDeviceLimits.h
- include/nbl/video/utilities/CDrawIndirectAllocator.h
- include/nbl/video/utilities/CSubpassKiln.h
- src/nbl/video/CVulkanLogicalDevice.h
- src/nbl/video/CVulkanPhysicalDevice.h
- src/nbl/video/ILogicalDevice.cpp
We either always enable or try to enable features on the Roadmap 2022 
https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#profile-features-roadmap-2022
No testing its going to be part of #503 
But should probably test the subpass kiln and whatever is using the Draw Indirect allocator.
- go through Descriptor Indexing stuff
> Vulkan Roadmap 2022

- include/nbl/builtin/hlsl/shapes/beziers.hlsl
Sister PR: https://github.com/Devsh-Graphics-Programming/Nabla-Examples-and-Tests/pull/52
> Changes to builtin HLSL code

- CMakeLists.txt
- include/nbl/builtin/hlsl/barycentric/utils.hlsl
- include/nbl/builtin/hlsl/cpp_compat/cpp_compat.h
- include/nbl/builtin/hlsl/cpp_compat/matrix.h
- include/nbl/builtin/hlsl/cpp_compat/vector.h
- include/nbl/builtin/hlsl/type_traits.hlsl
- src/nbl/builtin/CMakeLists.txt
- src/nbl/builtin/utils.cmake
> glm compat headers

- include/nbl/video/SPhysicalDeviceFeatures.h
Sorted our extensions by extension number according to https://raw.githubusercontent.com/KhronosGroup/Vulkan-Headers/main/registry/vk.xml
Filled in the gaps in extensions with comments that ext is not supported
> Extension order cleanup

- src/nbl/asset/utils/CHLSLCompiler.cpp
Checked that behaviour matched what it was previously, and that things were being invoked.
> Update tcpp version to include fixes from the original repository.

- src/nbl/video/ILogicalDevice.cpp
> Logical Device fix

- include/nbl/video/SPhysicalDeviceFeatures.h
- include/nbl/video/SPhysicalDeviceLimits.h
- src/nbl/video/ILogicalDevice.cpp
> Nahim devicefeatures

- include/nbl/system/CColoredStdoutLoggerANSI.h
ANSI Colored logger has a small bug, once a color is applied it doesn't come back after a process termination
> Fix colored logger bug

- include/nbl/builtin/hlsl/member_test_macros.hlsl
- include/nbl/builtin/hlsl/type_traits.hlsl
> Member test macros

- docker/scripts/build.py
> Nahim docker

- include/nbl/builtin/hlsl/device_capabilities_traits.hlsl
- include/nbl/builtin/hlsl/member_test_macros.hlsl
> Member test

- include/nbl/builtin/glsl/ies/functions.glsl
- include/nbl/builtin/glsl/material_compiler/common.glsl
- include/nbl/builtin/glsl/material_compiler/common_invariant_declarations.glsl
- include/nbl/ext/MitsubaLoader/SContext.h
- src/nbl/asset/interchange/CIESProfileLoader.cpp
- src/nbl/asset/material_compiler/CMaterialCompilerGLSLBackendCommon.cpp
- src/nbl/ext/MitsubaLoader/CMitsubaLoader.cpp
- src/nbl/ext/MitsubaLoader/CMitsubaMaterialCompilerFrontend.cpp
Continues from : https://github.com/Devsh-Graphics-Programming/Nabla/pull/630
> Continue with IES

- src/nbl/asset/interchange/CIESProfileLoader.cpp
- src/nbl/ext/MitsubaLoader/CMitsubaMaterialCompilerFrontend.cpp
> IES hot fixes

- include/nbl/video/alloc/SubAllocatedDescriptorSet.h
Some suggestions to optimize and make stuff correct
> improvement Suggestions

- include/nbl/system/CFileArchive.h
- include/nbl/system/IFileArchive.h
- include/nbl/video/utilities/ISimpleManagedSurface.h
- src/nbl/builtin/utils.cmake
> Example builtin resources fix

- tools/nsc/main.cpp
Updated nsc to remove references of ICPUSpecializedShader as it was obsolete.
> NSC Tool - new api

- .gitmodules
- 3rdparty/CMakeLists.txt
- include/nbl/asset/asset_utils.h
- include/nbl/builtin/hlsl/glsl_compat/core.hlsl
- include/nbl/builtin/hlsl/spirv_intrinsics/core.hlsl
- include/nbl/video/utilities/CDumbPresentationOracle.h
- include/nbl/video/utilities/IPresentationOracle.h
- src/nbl/ext/ImGui/ImGui.cpp
> ImGuizmo integration

- include/nbl/builtin/hlsl/subgroup/arithmetic_portability.hlsl
> Fix subgroupArithmetic error

- include/nbl/video/IGPUDescriptorSet.h
- include/nbl/video/utilities/IGPUObjectFromAssetConverter.h
> BufferView conversions and Buffer Upload fixes

- .gitmodules
- 3rdparty/CMakeLists.txt
update OpenEXR to latest
add IMath and Deflate submodule
force OpenEXR to use local deps (IMath & Deflate) instead of using fetchContent
compiles Nabla w/ and w/o `_NBL_COMPILE_WITH_OPEN_EXR_`
~~- [ ] remove unnecesary OpenEXR targets~~
> Update OpenEXR and spill out its deps

- src/nbl/asset/utils/CHLSLCompiler.cpp
> HLSL-Preprocessor fixes

- src/nbl/ext/ImGui/ImGui.cpp
> Imgui refactor of allocations

- src/nbl/asset/utils/CHLSLCompiler.cpp
> CHLSLCompiler: improve boost::wave exception error logging

- include/nbl/video/CVulkanSwapchain.h
- include/nbl/video/ISwapchain.h
- include/nbl/video/utilities/CSmoothResizeSurface.h
- include/nbl/video/utilities/ISimpleManagedSurface.h
- src/nbl/video/CVulkanSwapchain.cpp
https://github.com/Devsh-Graphics-Programming/Nabla-Examples-and-Tests/pull/158
> FramesInFlight and AcquiresInFlight

- src/nbl/video/utilities/CAssetConverter.cpp
> Dependent typename annotations on Asset Converter

- include/nbl/video/IGPUCommandBuffer.h
- src/nbl/video/IGPUCommandBuffer.cpp
> video: improve error logging in `IGPUCommandBuffer`

- src/nbl/builtin/CMakeLists.txt
> cmake: add missing builtin header

- src/nbl/asset/interchange/CImageLoaderPNG.cpp
> ditt branch: png loader: fix grayscale/alpha images bug

- tools/nsc/docker/README.md
Instruction to enable with `NBL_ENABLE_DOCKER_INTGRATION` option added
> Updated NSC readme

- include/nbl/builtin/hlsl/spirv_intrinsics/core.hlsl
@alichraghi test please and if good let me merge
> Stop bitcast emitting the BDA capability if bitcasting between SPIR-V builtin types

- include/nbl/core/hash/blake.h
- src/nbl/core/hash/blake.cpp
I used `reset()` in `IShaderCompiler.cpp` and ran CAD example
> blake3: add reset()

- include/nbl/asset/ICPUSampler.h
- include/nbl/asset/ISampler.h
- include/nbl/asset/filters/CBlitImageFilter.h
- include/nbl/asset/filters/CPaddedCopyImageFilter.h
- include/nbl/builtin/hlsl/enums.hlsl
- include/nbl/builtin/hlsl/prefix_sum_blur.hlsl
- include/nbl/builtin/hlsl/prefix_sum_blur/blur.hlsl
- include/nbl/builtin/hlsl/prefix_sum_blur/box_sampler.hlsl
- include/nbl/ext/FFT/FFT.h
- include/nbl/ext/MitsubaLoader/SContext.h
- include/nbl/video/CVulkanCommon.h
- src/nbl/asset/IAssetManager.cpp
- src/nbl/asset/interchange/CGLTFLoader.cpp
- src/nbl/asset/interchange/CGraphicsPipelineLoaderMTL.cpp
- src/nbl/asset/utils/CDerivativeMapCreator.cpp
- src/nbl/ext/DepthPyramidGenerator/DepthPyramidGenerator.cpp
- src/nbl/ext/ImGui/ImGui.cpp
- src/nbl/ext/LumaMeter/CLumaMeter.cpp
> Prefix sum box blur

- include/nbl/video/ILogicalDevice.h
> Fix false positive aspect mask error raising

- cmake/adjust/flags.cmake
- src/nbl/video/CVulkanCommandBuffer.cpp
- src/nbl/video/CVulkanCommandBuffer.h
> video: free command buffers when destroyed

- include/nbl/builtin/hlsl/cpp_compat/impl/intrinsics_impl.hlsl
- include/nbl/builtin/hlsl/emulated/float64_t.hlsl
- include/nbl/builtin/hlsl/emulated/float64_t_impl.hlsl
- include/nbl/builtin/hlsl/workgroup/fft.hlsl
> New tgmath

- CMakeLists.txt
- cmake/common.cmake
Installs docker on the machine if it's not present
Script tested on a clean Win10 VM without docker
> NBL_WITH_DOCKER cmake option

- include/nbl/video/IDeferredOperation.h
- include/nbl/video/IGPUAccelerationStructure.h
- include/nbl/video/IGPUCommandBuffer.h
- include/nbl/video/IGPUCommandPool.h
- include/nbl/video/ILogicalDevice.h
- include/nbl/video/IQueue.h
- src/nbl/video/IGPUCommandBuffer.cpp
- src/nbl/video/IQueue.cpp
…build counter (the iteration thats currently being stored)
Next are callbacks upon DeferredOperation and CommandBuffer completion
> TLAS tracking BLAS they use doing build

- include/nbl/system/demote_promote_writer_readers_lock.h
> Fixed Demote-Promote-Writer-Readers Lock

- include/nbl/core/containers/DoublyLinkedList.h
- include/nbl/core/containers/LRUCache.h
Cache Upgrades discussed in Discord: Iteration (both mutable and const), Eviction callback for whole pair, deep copy constructor
> Dtm lru cache upgrades

- include/nbl/builtin/hlsl/algorithm.hlsl
- include/nbl/builtin/hlsl/subgroup2/arithmetic_portability_impl.hlsl
> change to subgroup control barrier

- src/nbl/asset/utils/ISPIRVOptimizer.cpp
Fix spirv optimizer to skip validation
> Skip validation for spirv optimizer

- include/nbl/asset/ICPUAccelerationStructure.h
Fix AccelerationStructure::validBuildFlags infinite recursive call
> Fix AccelerationStructure::validBuildFlags infinite recursive call

- include/nbl/builtin/hlsl/cpp_compat/matrix.hlsl
Fix should be fine, but it's such a core component I'd like some reviews to be sure
> Fix small bug in matrix preventing product of unorthodox matrix sizes
