Devsh-Graphics-Programming/Nabla

examples_tests/48.ArithmeticUnitTest/main.cpp, examples_tests/48.ArithmeticUnitTest/shaderCommon.glsl, examples_tests/48.ArithmeticUnitTest/testWorkgroupExclusive.comp, examples_tests/48.ArithmeticUnitTest/testWorkgroupInclusive.comp, examples_tests/48.ArithmeticUnitTest/testWorkgroupReduce.comp, examples_tests/48.ArithmeticUnitTest/workgroupCommon.glsl, include/nbl/builtin/glsl/workgroup/ballot.glsl
Added a test for ballot bit count functions from `nbl/builtin/glsl/workgroup/ballot.glsl` to example 48.ArithmeticUnitTest
Additionally, after merging I encountered problems with CMeshManipulator.cpp, the template parameter count changed. Should this change be undone or is this ok?
=> Ballot test

include/nbl/asset/utils/IGLSLCompiler.h
conservativeEstimate also considers filePathHint and that is wrong.
=> Fixed origLen miscalculation

CMakeLists.txt, artifacts/CMakeLists.txt, examples_tests/22.RaytracedAO/Renderer.cpp, examples_tests/22.RaytracedAO/Renderer.h, examples_tests/22.RaytracedAO/main.cpp
1. .gitignore and CmakeLists.txt is all ok to merge
2. The submodules and dependencies
2a. SPIRV-Headers, SPIRV-Tools, glslang, shaderc, SPIRV-Cross don't matter which version they get upgraded to, you should probably get the latest stable anyway, cause that stuff fixes bugs and brings improvements and I do it periodically (careful though, all 4 need to be upgraded in sync cause they depend on each other, upgrading 1by1 wont work)
2b. RadeonRays you can just take from master
2c. Portable File Dialogs, just take latest stable tag
3. Readme, take from New API
4. Examples:
4a. 00 is new and temporary, leave
4b. 09 needs a fix in tryToWrite line 184
4c. 18 merge from master (it doesn't run on newAPI yet)
4d. 20-21 what happens is irrelevant
4e.  22 New API shouldn't have any changes to it, so …
=> Master to NewAPI

include/nbl/asset/utils/IGLSLCompiler.h, src/nbl/video/CVulkanPhysicalDevice.h
I added Vulkan 1.3 version to Vulkan version validation. To prevent show breakpoint ("Invalid Vulkan minor version!") when using Vulkan 1.3 SDK.
=> Add Vulkan 1.3 version to Vulkan version validation and Add Spir-v 1.6

include/nbl/builtin/glsl/math/functions.glsl, include/nbl/builtin/glsl/sampling/spherical_rectangle.glsl, include/nbl/builtin/glsl/shapes/rectangle.glsl, src/nbl/builtin/CMakeLists.txt
This is an implementation of spherical rectangle sampling that can potentially improve convergence of scenes with rectangular light source. It's basically an implementation of the paper below with possibly additional optimizations.
https://www.arnoldrenderer.com/research/egsr2013_spherical_rectangle.pdf
It was compared with triangle reference implmentation and they match the same output by my eye balling.
=> Spherical rectangle sampling

include/nbl/builtin/glsl/scanning_append/scanning_append.glsl, src/nbl/builtin/CMakeLists.txt
Console devs can suck it with their `__XB_GdsOrderedCount`
=> An alternative to the Indirect Scan

include/nbl/video/IPhysicalDevice.h
There was UB with format promotion due to uninitialized fields.
Example 06's promotion of the depth format.
=> Fix issue with SFormatImageUsage ctor

include/nbl/type_traits.h
vc143 was failing due to the is_any_of implementation (#416), I have reimplemented it using fold expressions
- Build works
- Added static_assert's as mini unit tests validating the results
=> Implement is_any_of using fold expression

include/nbl/ui/CWindowManagerWin32.h, include/nbl/ui/IWindow.h, include/nbl/ui/IWindowManager.h, include/nbl/ui/IWindowWin32.h
Currently, when resizing the window using the API call (`setWindowSize`) calls the event callback, but the result is unused as it doesn't stop the resize; Then, the event callback is called again, potentially with a new size including window borders and other possible calculations from Windows.
The maximum size returned by the surface capabilities should be taken into account when recreating the swapchain, as is done in the sister PR.
Sister PR: https://github.com/Devsh-Graphics-Programming/Nabla-Examples-and-Tests/pull/19
Example 09 was tested to not log the resizes twice.
=> Update setWindowSize & other window manager functions to ignore callback

include/nbl/asset/utils/CHLSLCompiler.h, src/nbl/asset/utils/CHLSLCompiler.cpp
Fixes encapsulation of DXC headers on CHLSLCompiler, allowing builds with Nabla as a lib to 1. work and 2. be fast
Verified with examples
=> Fix DXC encapsulation in CHLSLCompiler

include/nbl/system/ILogger.h
This crashes on linux, looks like its a use after free, i'm not actually sure why this works on windows? I guess the implementation is different or the list is not invalidated?
https://cplusplus.com/reference/cstdarg/va_list/
=> bugfix: resolve crash for va_list

include/nbl/asset/utils/CHLSLCompiler.h, src/nbl/asset/utils/CHLSLCompiler.cpp
Using unique ptr was causing issues with generating default destructor with undefined type, when Nabla was being used as a library.
Verified examples work and destructors get called.
=> Go back from using unique ptr for DXC

include/nbl/video/IPhysicalDevice.h, include/nbl/video/utilities/IUtilities.h
this is a workaround to a crash observed and tested against clang-14,15,16 for linux. the workaround is just to expand the templates themselves so its quite a bit more verbose then the original code. it doesn't seem too bad though, made sure to keep the API basically the same. 
ref: https://github.com/llvm/llvm-project/issues/60938#issuecomment-1442706682
=> bugfix: address crash releated to clang when compiling promoteBufferFormat or promoteImageFormat

include/nbl/core/containers/CMemoryPool.h
is_pod_v is deprecated in C++20 this replaces the same line with `is_trivial`
https://en.cppreference.com/w/cpp/types/is_trivial
=> chore: is_pod is deprecated replace with is_trivial

include/nbl/asset/utils/IShaderCompiler.h, src/nbl/asset/utils/CCompilerSet.cpp, src/nbl/asset/utils/CHLSLCompiler.cpp, src/nbl/asset/utils/IShaderCompiler.cpp
- Adds support for custom spirv optimizer settings
- Returns the spirv shader directly on preprocess shader
- Compilation was tested with and without a custom optimizer
=> HLSL compiler updates

include/nbl/core/memory/memory.h, include/nbl/video/IGPUCommandPool.h
I was observing an assertion on IGPUCommandPool.
```
Alloc'ed 0x5555573aec80 with 56
Alloc'ed 0x5555573749c0 with 56
Alloc'ed 0x555556e9b230 with 56
Alloc'ed 0x555556e9c4d0 with 56
Alloc'ed 0x5555571e8410 with 128
Alloc'ed 0x555556ea5610 with 128
Alloc'ed 0x555556eaabc0 with 128
Alloc'ed 0x5555573fd0c0 with 128
Alloc'ed 0x55555734a090 with 128
Alloc'ed 0x7fffddfff010 with 33556544
helloworld_d: /home/michaelpollind/projects/Nabla/include/nbl/video/IGPUCommandPool.h:66: nbl::video::IGPUCommandPool::ICommand::ICommand(uint32_t): Assertion `ptrdiff_t(this) % alignof(ICommand) == 0' failed.
Thread 1 "helloworld_d" received signal SIGABRT, Aborted.
```
by default the pool allocates on a 16 bit boundary so 0x7fffddfff010 is a multiple of 16 but not 64.
=> bugfix: address memory assertions for command pool

include/nbl/system/CFileArchive.h, include/nbl/system/atomic_state.h, src/nbl/builtin/CMakeLists.txt, src/nbl/builtin/builtinHeaderGen.py, src/nbl/builtin/template/CArchive.h.in, src/nbl/builtin/utils.cmake
Require Nabla to be linked into BRs libraries due to some codebase symbols, add SHARED builtin-resources test to examples 52. Apply some fixes and mute IntelliSense in builtin-resources headers
=> Make SHARED builtin-resources builds work

include/nbl/asset/IImage.h, include/nbl/asset/IImageView.h, include/nbl/asset/filters/CBlitImageFilter.h, include/nbl/asset/filters/CCopyImageFilter.h, include/nbl/asset/filters/CMipMapGenerationImageFilter.h, include/nbl/asset/filters/CNormalMapToDerivativeFilter.h, include/nbl/asset/filters/CSwizzleAndConvertImageFilter.h, include/nbl/asset/filters/NormalizationStates.h, include/nbl/asset/utils/CDerivativeMapCreator.h, include/nbl/asset/utils/ICPUVirtualTexture.h, include/nbl/asset/utils/IVirtualTexture.h, include/nbl/builtin/shader/loader/mtl/fragment_impl.glsl, include/nbl/ext/OIT/OIT.h, include/nbl/ext/ScreenShot/ScreenShot.h, include/nbl/ext/ToneMapper/CToneMapper.h, include/nbl/video/IGPUImage.h, include/nbl/video/utilities/IGPUObjectFromAssetConverter.h, include/nbl/video/utilities/IGPUVirtualTexture.h, src/nbl/asset/IAssetManager.cpp, src/nbl/asset/interchange/CGLILoader.cpp, src/nbl/asset/interchange/CGraphicsPipelineLoaderMTL.cpp, src/nbl/asset/utils/CDerivativeMapCreator.cpp, src/nbl/video/CVulkanCommandBuffer.cpp, src/nbl/video/CVulkanImageView.h, src/nbl/video/CVulkanLogicalDevice.h, src/nbl/video/CVulkanPhysicalDevice.h, src/nbl/video/IGPUCommandBuffer.cpp
Fixes:
- querying for device properties and limits for extensions that are not supported (dynamic pNext chain construction)
- querying format usages for formats which are not supported (no extension or vulkan instance version)
- not generating mip-maps for images that already have defined mip pyramids (like KTX/DDS)
- only make the mip-pyramid full if there was no mip-pyramid to start with in the first place
- fix #411 
- upstream a bunch of fixes from `ditt` branch
- minor issues with compilation of certain examples
Just running examples, nothing complex like comparing device props and limit structs before and after implementing changes.
Actually fix #472
=> Fix Validation Errors and Bumpmaps

include/nbl/system/CFileArchive.h, include/nbl/system/CMountDirectoryArchive.h, include/nbl/system/IFileArchive.h, src/nbl/system/IFileArchive.cpp
In this PR `IFileArchive::listAssets(const path& pathRelativeToArchive)` method was changed to no longer be virtual, to take a parameter that is not const and its implementation was changed to return lexicographically in range matches.
Because the match range's bounds are not easy to imagine, i wrote a long comment explaining what is happening.
`IFileArchive::m_items` became private, and can be assigned via protected method
=> Mount directories fix

include/nbl/asset/utils/CSPIRVIntrospector.h, include/nbl/asset/utils/IShaderCompiler.h, include/nbl/core/util/bitflag.h, src/nbl/asset/utils/CGLSLCompiler.cpp, src/nbl/asset/utils/CHLSLCompiler.cpp, src/nbl/video/CVulkanLogicalDevice.h
instead of a single bool for genDebugInfo in shader compiler options, we now have a flag with different options mimicking spv debug options of dxc
Tested examplle 62 and 29 where they use the compiler and introspector respectively
Everything is done
=> E_DEBUG_LEVEL_INFO

include/nbl/asset/ICommandBuffer.h, include/nbl/video/CThreadSafeGPUQueueAdapter.h, include/nbl/video/IGPUQueue.h, include/nbl/video/decl/IBackendObject.h, src/nbl/video/CVulkanCommandBuffer.h, src/nbl/video/CVulkanQueue.cpp, src/nbl/video/CVulkanQueue.h
Implement DebugMarker functionalities in ext_debug_utils extension:
- [vkCmdBeginDebugUtilsLabelEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBeginDebugUtilsLabelEXT.html)
- [vkCmdEndDebugUtilsLabelEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdEndDebugUtilsLabelEXT.html)
- [vkCmdInsertDebugUtilsLabelEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdInsertDebugUtilsLabelEXT.html)
- [vkQueueBeginDebugUtilsLabelEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkQueueBeginDebugUtilsLabelEXT.html)
- [vkQueueEndDebugUtilsLabelEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkQueueEndDebugUtilsLabelEXT.html)
- …
=> Implement debugMarkers

3rdparty/dxc/CMakeLists.txt, src/nbl/asset/utils/CHLSLCompiler.cpp, src/nbl/system/ISystem.cpp
Change spirv headers on dxc 3rdparty CMake script to be included using spirv/<VERSION>/<HEADERFILE>
SPIRV headers are now included using a proper path that matches the file structure under the `include/` dir.
Include any spirv header in a shader such as `spirv/1.2/spirv.h`
-
=> Change spirv headers path

include/nbl/builtin/hlsl/cpp_compat.hlsl
Make NBL_(CONST)_REF_ARG to work with multi-parameter templates.
Godbolt DXC latest.
=> Make NBL_(CONST)_REF_ARG to work with multi-parameter templates.

include/nbl/builtin/hlsl/glsl_compat/core.hlsl
`glsl::atomicAdd` was calling `spirv::atomicAnd`
N/A
N/A
=> fix glsl compat code for atomicADD calling spriv atomicAND instead of ADD

include/nbl/video/IGPUDescriptorSet.h, include/nbl/video/ILogicalDevice.h, include/nbl/video/alloc/SubAllocatedDescriptorSet.h, src/nbl/video/CVulkanLogicalDevice.cpp, src/nbl/video/CVulkanLogicalDevice.h, src/nbl/video/ILogicalDevice.cpp
=> Suballocated Descriptor Set PR Review Fixes

include/nbl/builtin/hlsl/cpp_compat/promote.hlsl
Changed the Promote struct so that it only works with proper Scalars and saving a lot of boilerplate specialization code
Ran fine on the complex FFT tests (coming to a new example on the examples repo)
=> Better templated Promote struct

include/nbl/builtin/hlsl/type_traits.hlsl
Forgot about these I had added to `type_traits.hlsl` which are needed for bitfield insert to work (also for `glsl_compat/core.hlsl` to compile since it has bitfield insert in it now)
=> Forgot about these when I pushed the bitfield insert

src/nbl/device/DeviceGen.py
fixes an issue where: device headers (_device capabilities traits_ and _physical device features_) are not generated
tested on `python 3.9.0`
**steps to reproduce the issue:**
1. clone Nabla (`git clone --depth 1 git@github.com:Devsh-Graphics-Programming/Nabla.git`)
or clear existing repo (`git clear -f -d`)
2. [re]generate Visual Studio project with CMake (i.e. `cmake .` in CLI)
3. open `Nabla.sln` solution, build `DeviceHeaders` project
**expected result:**
project generates HLSL and C headers (i.e. `device_capabilities_traits_enums.hlsl`)
**actual result:**
`DeviceGen.py` throws an exception:
```
63>Error while writing to file: E:/Projects/Vulkan/NablaFork/src/nbl/device/include/nbl/video/SPhysicalDeviceFeatures_members.h
63>Exception: name 'Expose' is not defined
63>Traceback (most …
```
=> fix device headers generation script

src/nbl/asset/interchange/CGLILoader.cpp, src/nbl/asset/interchange/CImageHasher.h, src/nbl/asset/interchange/CImageLoaderJPG.cpp, src/nbl/asset/interchange/CImageLoaderOpenEXR.cpp
moves content hash computation into image loading loop - for JPEG, GLI (OpenGL Image), OpenEXR (_only these were marked for todo_)
extends `CImageHasher` (adds inline methods for _sequential hash calculation_)
passes `NBL_IMAGE_HASH_RUN_TESTS` with `Debug` configuration
=> Inline image content hash computation

include/nbl/asset/ICPUImage.h, include/nbl/asset/filters/CBasicImageFilterCommon.h, include/nbl/asset/filters/CBlitImageFilter.h, include/nbl/asset/filters/CCopyImageFilter.h, include/nbl/asset/filters/CFillImageFilter.h, include/nbl/asset/filters/CMatchedSizeInOutImageFilterCommon.h, include/nbl/asset/filters/CRegionBlockFunctorFilter.h, include/nbl/asset/filters/CSummedAreaTableImageFilter.h, include/nbl/asset/filters/CSwizzleAndConvertImageFilter.h, include/nbl/asset/filters/dithering/CPrecomputedDither.h, include/nbl/asset/interchange/IImageAssetHandlerBase.h, src/nbl/asset/ICPUImage.cpp, src/nbl/asset/interchange/CGLIWriter.cpp, src/nbl/asset/interchange/CImageLoaderOpenEXR.cpp, src/nbl/asset/interchange/CImageWriterOpenEXR.cpp
shallowly updates `getRegions()` in `ICPUImage.h` (_and methods explicit usages_) to use `std::span<>`
to obtain raw pointers (required by some methods) `<span>.data()` and `<span>.data() + <span>.size()` is used, since it's the only method to access raw pointers without dereferencing iterators
> dereferencing `.end()` iterator may cause address violation segfault
passes 24_ColorSpaceTest (requires a patch - see [0aa4c5](https://github.com/tad1/Nabla-Examples-and-Tests/commit/0aa4c5e7f3a5e3ce6680cbdac7ba022d1d99e8be))
=> update getRegions() to return std::span<> instead of core::SRange<>

src/nbl/builtin/builtinHeaderGen.py
fixes warning:
```
74>------ Build started: Project: extGizmoSpirvBuiltinResourceData, Configuration: Debug x64 ------
74>1>Generating "extGizmoSpirvBuiltinResourceData"'s sources & headers
74>D:\work\Nabla-master\src\nbl\builtin\builtinHeaderGen.py:47: SyntaxWarning: invalid escape sequence '\w'
74>  """)
```
which shows on some Python versions
checked, and tested 24th example (normal mode)
=> remove Python warning in builtinHeaderGen.py

include/nbl/builtin/hlsl/bda/bda_accessor.hlsl
Adds a BdaAccessor variant that reads from a ptr and writes to another ptr. Also templates BdaAccessor's atomics so SFINAE resolution doesn't impede instancing for non-integral accessors
Worked fine replacing the DoublePtr in example 10
Nothing
=> Adds new DoubleBdaAccessor

src/nbl/video/device_capabilities/device_features.json
in https://github.com/Devsh-Graphics-Programming/Nabla/commit/21d6979d44837d5f31ba7552236e9d2a1b6b1826, `alphaToOne` was set to `false` but somehow regressed later.
I was able to run helloswapchain example after this change.
=> device_features: actually disable `alphaToOne`

.gitmodules, 3rdparty/CMakeLists.txt
Applies #730 patch to the master
prevent OpenEXR's fetch by spilling out it's dependencies and updating OpenEXR submodule (previous version would require additional workarounds)
builds and runs: nabla, 24th example
=> remove fetch from OpenEXR

include/nabla.h
When compiling Nabla as a DLL, the NBL_API2 macro is being used before it is defined when importing the nabla.h header. This means we can't compile it. I've changed the order around to make sure this works.
=> Fix issue with nabla.h gitinfo

include/nbl/asset/utils/ISPIRVOptimizer.h, src/nbl/asset/utils/ISPIRVOptimizer.cpp, src/nbl/asset/utils/shaderCompiler_serialization.h
- There's a disabled optimizer pass so I pushed it to the bottom of the enum (otherwise it fucks up the retrieval later). 
- Update SPIRV version for the optimizer (was at 1.5, now 1.6).
- Change optimizer's message callback so it doesn't crash on nullpointer deref
- Fix a slight overlook when I made serialization of optimizer passes
Added an optimizer pass to my FFT_Bloom example and it worked fine. Caching worked fine as well.
=> Small fix for SPIRV Optimizer + small fix to optimizer pass serialization

include/nbl/builtin/hlsl/cpp_compat/impl/intrinsics_impl.hlsl, include/nbl/builtin/hlsl/cpp_compat/intrinsics.hlsl, include/nbl/builtin/hlsl/glsl_compat/core.hlsl, include/nbl/builtin/hlsl/spirv_intrinsics/core.hlsl
Adds SPIR-V's `OpBitReverse` intrinsic, using glm's implementation on cpp side
Checked that glm did the same as the spir-v intrinsic by running a small program
=> Bitreverse intrinsic

src/nbl/asset/interchange/CImageLoaderPNG.cpp
=> png loader: fix grayscale/alpha images bug

include/nbl/builtin/hlsl/cpp_compat/impl/intrinsics_impl.hlsl, include/nbl/builtin/hlsl/math/functions.hlsl, include/nbl/builtin/hlsl/shapes/beziers.hlsl
=> Fixed some hlsl functions

include/nbl/asset/utils/CHLSLCompiler.h, include/nbl/builtin/hlsl/bda/__ref.hlsl, include/nbl/builtin/hlsl/spirv_intrinsics/core.hlsl, include/nbl/builtin/hlsl/spirv_intrinsics/fragment_shader_barycentric.hlsl, include/nbl/builtin/hlsl/spirv_intrinsics/subgroup_arithmetic.hlsl, include/nbl/builtin/hlsl/spirv_intrinsics/subgroup_vote.hlsl, src/nbl/asset/utils/CHLSLCompiler.cpp, src/nbl/builtin/CMakeLists.txt
=> DXC member decorate, Spir-V 1.4 backports and KHR_fragment_shader_barycentrics support

include/nbl/asset/IAccelerationStructure.h, include/nbl/asset/ICPUAccelerationStructure.h, include/nbl/asset/IDescriptorSetLayout.h, include/nbl/video/IDeferredOperation.h, include/nbl/video/ILogicalDevice.h, include/nbl/video/utilities/CAssetConverter.h, src/nbl/video/utilities/CAssetConverter.cpp
Conversion of ICPU BLAS and TLAS to IGPU including building.
We may need to support a list of IGPUBLAS in IGPUTLAS for sanity/lifetime coupling, but only if update/rebuild is not allowed or something (need to make a separate issue out of it because I have no clue how that's gonna be structured).
=> Acceleration Structure Conversion

include/nbl/asset/material_compiler/v2/IR.h, include/nbl/asset/material_compiler/v2/IRNode.h, include/nbl/core/ApplyMacro.h, include/nbl/core/math/fnvhash.h, src/nbl/CMakeLists.txt, src/nbl/asset/material_compiler/v2/IRNode.cpp
Very rough draft that shows new IR interface with POC insert_subdag, dead_strip, subexpression_elimination implementation.
It introduces "Value" abstraction that tries to solve multiple issues:
- Now don't have to maintain "children" array even if the node will not ever have children list
- Proper hashing of "normal mapped" subtree; by having normal "Value" inside all bsdf node if bsdf uses different normal, the hash of subtree will be different
- Arbitrary subexpression elimination can remove unnecessary texture prefetch or normal precomputation without need of separate pass (just typical subexpression elimination will remove it since hash is same)
- Open up possibility of supporting arbitrary expression (not major point but nice to have)
- Make code compile
- Testing infrastructure
- …
=> Material compiler v2
